# Data Sources
input:
  data_dir: "data"
  file_pattern: "*.csv"

# Data Processing Parameters
processing:
  time_alignment:
    resample_freq: "1T"  # 1 minute
    fill_method: "ffill"
  join_keys:
    - "timestamp"
    - "symbol"

# Feature Engineering Parameters
features:
  technical_indicators:
    sma_windows: [3, 5, 10]  # Shorter windows for small datasets
    ema_windows: [3, 5, 10]
    rsi_period: 5
    bollinger_bands:
      window: 5
      num_std: 2
    macd:
      fast_period: 6
      slow_period: 12
      signal_period: 4
    adx_period: 5  # For trend strength detection
  
  volatility:
    std_windows: [3, 5, 10]
    
  lags:
    price_lags: [1, 2, 3]
    volume_lags: [1, 2]

  # Market Regime Detection
  regime_detection:
    enabled: true
    volatility:
      source: "rolling_stddev"  # Options: "atr" or "rolling_stddev"
      window: 5
      thresholds:
        low: 0.01   # Below this is considered low volatility
        high: 0.03  # Above this is considered high volatility
    trend:
      enabled: true
      method: "sma"  # Using SMA for trend strength
      threshold: 25  # SMA above this indicates strong trend
      ma_comparison: true  # Also use MA slope for trend direction
      ma_window: 5
    
  # New: Signal Generation
  signal_generation:
    enabled: true
    macd:
      signal_cross_enabled: true
      zero_cross_enabled: true
    rsi:
      enabled: true
      oversold: 30
      overbought: 70
    ma_crossover:
      enabled: true
      fast_ma: 3
      slow_ma: 5
    volume_surge:
      enabled: true
      threshold: 2.0  # Multiple of average volume
      window: 5
    
  anomaly_detection:
    z_score_window: 5
    threshold: 3.0
    
  statistical_features:
    rolling_window: 30
    target_columns: ['price']
    metrics: ['skew', 'kurt']
    
  interaction_features:
    pairs:
      - ['price', 'volume']
      - ['price', 'rsi']
      - ['volume', 'macd']
    types: ['multiply', 'ratio']

# Anomaly Detection Parameters
anomaly_detection:
  enabled: true
  method: 'IsolationForest'
  features_to_use:
    - 'price'
    - 'volume'
    - 'rsi'
    - 'macd'
    - 'price_rolling_skew_30'
    - 'price_rolling_kurt_30'
    - 'price_volume_multiply'
    - 'volatility_20'
  contamination: 'auto'
  n_estimators: 100
  max_samples: 'auto'
  random_state: 42
  output_column_name: 'anomaly_flag_iforest'

# Statistical Analysis Parameters
statistical_analysis:
  enabled: true
  # --- Stationarity Tests ---
  stationarity_tests:
    run_adf: true
    columns_to_test:
      - 'price'
      - 'volume'
      - 'rsi'
      - 'macd'
      - 'volatility_20'
      - 'price_zscore'
      - 'price_rolling_skew_30'
      - 'price_rolling_kurt_30'
    adf_significance_level: 0.05
  # --- Granger Causality Tests ---
  granger_causality_tests:
    run_granger: true
    max_lag: 5
    pairs_to_test:
      - [['price'], ['volume']]  # Test if volume Granger-causes price
      - [['price'], ['rsi']]     # Test if RSI Granger-causes price
      - [['price'], ['macd']]    # Test if MACD Granger-causes price
      - [['volume'], ['volatility_20']]  # Test if volatility Granger-causes volume
      - [['price'], ['bb_upper', 'bb_lower']]  # Test if Bollinger Bands Granger-cause price
    granger_significance_level: 0.05
  # --- Output ---
  results_output_file: "outputs/web_dashboard/statistical_test_results.json"

# HMM Analysis Parameters
hmm_analysis:
  enabled: true
  n_hidden_states: 2  # Reduced states for small datasets
  
  # Covariance type determines how feature relationships are modeled within states:
  # - 'spherical': Simplest model. Features independent, same variance. Best for scaled, uncorrelated features.
  # - 'diag': Features independent, different variances. Good default choice.
  # - 'full': Features can be correlated within states. Most flexible but needs more data.
  # - 'tied': All states share same covariance matrix. Middle ground between diag and full.
  covariance_type: "diag"
  
  n_iterations: 2000  # Increased from 100 to improve convergence
  n_init: 10         # Number of times to run fitting with different initializations
  random_state: 42   # For reproducibility
  
  # Features used to detect market regimes
  features_to_use:
    - "log_return"      # Price movement
    - "volume"          # Volume
    - "volatility_5"    # Market volatility
    - "rsi"            # Momentum
    - "macd"           # Trend
  
  output_column_name: "hmm_regime"  # Column name for detected states
  
  # Feature scaling options
  feature_scaling:
    enabled: true
    method: "robust"  # More robust to outliers

# New: LLM Output Generation Parameters
llm_output_generation:
  enabled: true
  output_file: "outputs/llm_insights/run_summary.md"
  
  # Content inclusion flags
  include_statistical_summary: true
  include_anomaly_summary: true
  include_hmm_summary: true
  include_regime_summary: true
  include_recent_signal_summary: true
  include_data_quality_summary: true    # New: control data quality section
  include_state_characteristics: true   # New: control state characteristics analysis
  include_state_persistence: true       # New: control state persistence analysis
  
  # Analysis periods for recent summaries
  summary_periods: [5, 10, 20]
  
  # File paths for auxiliary data
  hmm_interpretations_file: "outputs/web_dashboard/hmm_interpretations.json"
  statistical_results_file: "outputs/web_dashboard/statistical_test_results.json"
  
  # New: State characteristics analysis configuration
  state_characteristics:
    target_columns:
      - "price"
      - "volume"
      - "volatility_5"
      - "rsi"
      - "macd"
    metrics:
      - "mean"
      - "std"
      - "median"
      - "min"
      - "max"
  
  # New: Data quality analysis configuration
  data_quality:
    time_gap_threshold: "1H"    # Maximum acceptable time gap
    significant_missing_threshold: 1.0  # % threshold for reporting missing data
    check_columns:  # Columns to check for quality issues
      - "price"
      - "volume"
      - "rsi"
      - "macd"
      - "volatility_5"

# Output Settings
output:
  trading_model:
    path: "outputs/trading_model/features.parquet"
    compression: "snappy"
  
  dashboard:
    path: "outputs/web_dashboard"
    plot_format: "html"  # Changed from json to html for interactive plots
    interactive: true

# Visualization Settings
visualization:
  # Time series decomposition settings
  plot_decomposition: true
  decomposition_column: 'price'
  decomposition_model: 'additive'
  decomposition_period: 5  # Shorter period for small datasets

  # Feature distribution plots
  plot_feature_distributions: true
  distribution_columns:
    - 'price'
    - 'volume'
    - 'volatility_5'
    - 'rsi'

  # Anomaly visualization
  plot_anomalies_on_timeseries: true
  anomaly_flag_column: 'anomaly_flag_iforest'
  timeseries_base_column: 'price'

  # Statistical test visualization
  plot_statistical_tests: true
  correlation_heatmap_columns:
    - 'price'
    - 'volume'
    - 'volatility_5'
    - 'rsi'

  # HMM visualization settings
  hmm_visualization:
    enabled: true
    regime_colors:
      volatile_bullish: 'rgba(0, 255, 0, 0.2)'   # Green
      volatile_bearish: 'rgba(255, 0, 0, 0.2)'   # Red
      calm_neutral: 'rgba(128, 128, 128, 0.2)'   # Gray
    show_annotations: true
    show_probabilities: true
    probability_window: 20  # Window for rolling probabilities

# Logging Configuration
logging:
  level: "INFO"
  file: "pipeline.log"

data:
  raw_data_dir: "data/raw"
  zip_file: "round-2-island-data-bottle.zip"

feature_config:
  technical_indicators:
    enabled: true
    rsi:
      window: 14
    macd:
      fast: 12
      slow: 26
      signal: 9
    bollinger:
      window: 20
      num_std: 2

  regime_detection:
    volatility:
      enabled: true
      window: 20
      thresholds:
        low_vol: 0.5
        high_vol: 2.0
    trend:
      enabled: true
      window: 50

  signal_generation:
    macd:
      signal_cross_enabled: true
      zero_cross_enabled: true
    rsi:
      enabled: true
      oversold: 30
      overbought: 70
    ma_crossover:
      enabled: true
      fast_ma: 10
      slow_ma: 30
    volume_surge:
      enabled: true
      window: 20
      threshold: 2.0

output_config:
  features_file: "outputs/trading_model/features.parquet"
  visualization_dir: "outputs/web_dashboard"
  llm_output_dir: "outputs/llm_insights"